"""Pipeline stage: convert self-contained HTML/Markdown reports to PDF.

The report files generated by visualizations.py are saved with a .md suffix,
and currently mix an HTML shell with Markdown headings and raw HTML blocks.
This stage renders the Markdown body to HTML, preserves the existing head/CSS,
and then uses a headless Chromium-based browser (preferably Edge on Windows)
to print the temporary .html file to PDF.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import time
from pathlib import Path

from markdown_it import MarkdownIt

from .paths import RunPaths, ensure_run_dirs


_BROWSER_NAMES = [
    "msedge",
    "microsoft-edge",
    "chrome",
    "google-chrome",
    "chromium",
    "chromium-browser",
]

_BROWSER_CANDIDATES = [
    Path("C:/Program Files/Microsoft/Edge/Application/msedge.exe"),
    Path("C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"),
    Path("C:/Program Files/Google/Chrome/Application/chrome.exe"),
    Path("C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"),
]

_HTML_BODY_RE = re.compile(
    r"(?is)(?P<prefix>.*?<body[^>]*>)(?P<body>.*?)(?P<suffix></body>\s*</html>\s*)\Z"
)
_MARKDOWN_RENDERER = MarkdownIt("commonmark", {"html": True})


def _find_browser() -> Path:
    for name in _BROWSER_NAMES:
        resolved = shutil.which(name)
        if resolved:
            return Path(resolved)

    for candidate in _BROWSER_CANDIDATES:
        if candidate.exists():
            return candidate

    raise RuntimeError(
        "Nenhum navegador Chromium compatível foi encontrado. "
        "Instale Microsoft Edge ou Google Chrome, ou adicione o executável ao PATH."
    )


def _html_export_path(report_path: Path) -> Path:
    return report_path.with_suffix(".export.html")


def _report_text_to_html(report_text: str) -> str:
    match = _HTML_BODY_RE.match(report_text)
    if match:
        body_html = _MARKDOWN_RENDERER.render(match.group("body").strip())
        return f"{match.group('prefix')}\n{body_html}\n{match.group('suffix')}"
    return _MARKDOWN_RENDERER.render(report_text)


def _render_pdf(browser: Path, report_path: Path, pdf_path: Path) -> None:
    if not report_path.exists():
        raise FileNotFoundError(
            f"Relatório não encontrado: {report_path}. "
            "Execute primeiro o estágio report-viz."
        )

    html_path = _html_export_path(report_path)
    report_text = report_path.read_text(encoding="utf-8")
    html_path.write_text(_report_text_to_html(report_text), encoding="utf-8")
    pdf_path.unlink(missing_ok=True)

    cmd = [
        str(browser),
        "--headless",
        "--disable-gpu",
        "--allow-file-access-from-files",
        "--no-pdf-header-footer",
        "--print-to-pdf-no-header",
        f"--print-to-pdf={pdf_path}",
        html_path.resolve().as_uri(),
    ]

    try:
        completed = subprocess.run(cmd, check=True, capture_output=True, text=True)
        _ = completed
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or str(exc)).strip()
        raise RuntimeError(
            f"Falha ao exportar {report_path.name} para PDF. "
            f"HTML temporário mantido em {html_path}. Detalhe: {detail}"
        ) from exc

    deadline = time.monotonic() + 15.0
    last_size = -1
    stable_hits = 0
    while time.monotonic() < deadline:
        if pdf_path.exists():
            current_size = pdf_path.stat().st_size
            if current_size > 0:
                if current_size == last_size:
                    stable_hits += 1
                else:
                    stable_hits = 0
                last_size = current_size
                if stable_hits >= 1:
                    break
        time.sleep(0.25)

    if not pdf_path.exists() or pdf_path.stat().st_size == 0:
        raise RuntimeError(
            f"Falha ao gerar {pdf_path.name}: o arquivo PDF não foi criado corretamente."
        )

    html_path.unlink(missing_ok=True)


def run(paths: RunPaths) -> None:
    ensure_run_dirs(paths)
    browser = _find_browser()
    print(f"[report-pdf] Navegador: {browser}")

    exports = [
        (paths.report_dark_path, paths.report_pdf_path),
        (paths.report_light_path, paths.report_light_pdf_path),
    ]

    for report_path, pdf_path in exports:
        print(f"[report-pdf] Exportando {report_path.name} -> {pdf_path.name}")
        _render_pdf(browser, report_path, pdf_path)
        size_kb = pdf_path.stat().st_size // 1024
        print(f"[report-pdf] Salvo: {pdf_path} ({size_kb} KB)")